apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-data-pv
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Name }}-data-pv
spec:
  storageClassName: nfs
  capacity:
    storage: {{ .Values.pv.capacity.data }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.pv.server }}
    path: "/volume1/cluster-data/{{ .Release.Name }}/data"
  persistentVolumeReclaimPolicy: Retain